name: MTG Data Pipeline

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC daily
  workflow_dispatch: # Allows manual runs from GitHub UI

# Environment variables used by all jobs
env:
  IMAGE_NAME: mtg-pipeline

# Define jobs
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Check out repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # Build Docker image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      # Run pipeline
      - name: Run pipeline
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: |
          docker run --rm \
            -e POSTGRES_URL=$POSTGRES_URL \
            $IMAGE_NAME

      # Send Discord notification
      - name: Send Discord notification
        if: always()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            🎲 MTG Pipeline run completed with status: ${{ job.status }}
            📋 View run details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
